/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  LiquidityControl,
  LiquidityControlInterface,
} from "../LiquidityControl";

const _abi = [
  {
    inputs: [],
    name: "sessionLiquidityChangeLimit",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "newLimit",
        type: "uint256",
      },
    ],
    name: "setLiquidityChangeLimit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class LiquidityControl__factory {
  static readonly abi = _abi;
  static createInterface(): LiquidityControlInterface {
    return new utils.Interface(_abi) as LiquidityControlInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LiquidityControl {
    return new Contract(address, _abi, signerOrProvider) as LiquidityControl;
  }
}
